config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root "foods#index"
  resources :foods
  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    member do
      patch :toggle_public
      get :shopping_list
    end

    resources :recipe_foods, only: [:new, :create, :edit, :update,  :destroy]
  end

  resources :shopping_lists, only: [:index]
  
  get 'users', to: 'users#index'

  root "foods#index"
  resources :public_recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food, class_name: 'Food', foreign_key: 'food_id'
  belongs_to :recipe, class_name: 'Recipe', foreign_key: 'recipe_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :foods
  has_many :recipes

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :authenticate_user!, except: %i[index show]

  protected

  def configure_permitted_parameters
    attributes = [:name]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods
  def index
    @foods = current_user.foods
  end

  # GET /foods/1
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods
  def create
    @food = Food.new(food_params)
    @food.user = current_user

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_url(@food), notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def set_food
    @food = Food.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.includes(:user).where(public: true).order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe = Recipe.find_by(id: params[:recipe_id])
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe = Recipe.find_by(id: params[:recipe_id])
    @food_ids = RecipeFood.where(recipe_id: @recipe.id).map(&:food_id)

    if @food_ids.include?(recipe_food_params[:food_id].to_i)
      return redirect_to recipe_path(@recipe.id),
                         alert: 'Recipe already has this ingredient!'
    end

    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe_id = @recipe.id

    if @recipe_food.save
      flash[:notice] = 'Ingredients added successfully'
    else
      flash[:alert] = 'Failed to add Ingredients!'
    end
    redirect_to recipe_path(@recipe)
  end

  def edit
    @recipe = Recipe.find_by(id: params[:recipe_id])
    @recipe_food = RecipeFood.includes(:recipe).find_by(id: params[:id])
  end

  def update
    @recipe = Recipe.find_by(id: params[:recipe_id])
    @recipe_food = RecipeFood.includes(:recipe).find_by(id: params[:id])
    puts @recipe

    if @recipe_food.update(recipe_food_params)
      flash[:notice] = 'Ingredient has been updated successfully'
      redirect_to recipe_path(@recipe.id)
    else
      flash[:alert] = 'Failed to update Ingredient!'
      redirect_to recipe_path(@recipe)
    end
  end

  def destroy
    @recipe_food = RecipeFood.includes(:recipe).find_by(id: params[:id])

    if @recipe_food.destroy
      flash[:notice] = 'Ingedrient removed successfully.'
    else
      flash[:alert] = 'Failed to delete the ingredient!'
    end
    redirect_to recipe_path(id: params[:recipe_id])
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = Recipe.includes([:user]).where(user_id: current_user.id).order(created_at: :desc)
  end

  def public_recipes
    @recipes = Recipe.includes(:user, :foods).where(public: true).order(created_at: :desc)
  end

  def show
    @recipe = Recipe.find(params[:id])
    @user = current_user
    @recipe_foods = RecipeFood.includes(:recipe).where(recipe_id: @recipe.id)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    if @recipe.save
      flash[:notice] = 'Saved Successfully'
      redirect_to recipes_path
    else
      flash[:alert] = 'Failed to save!'
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])

    if @recipe.destroy
      flash[:notice] = 'Deleted Successfully'
    else
      flash[:alert] = 'Failed to delete!'
    end
    redirect_to recipes_path
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)
    redirect_to recipe_path(@recipe)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user

    recipe_foods = @user.recipes.joins(:foods).select('foods.*')
    general_foods = @user.foods

    @missing_foods = recipe_foods - general_foods

    @total_food_items = @missing_foods.count
    @total_price = calculate_total_price(@missing_foods)

    @result = {
      missing_items: @total_food_items,
      total_price: @total_price,
      items: @missing_foods.map do |food|
               { name: food.name, quantity: food.quantity, measurement_unit: food.measurement_unit, price: food.price }
             end
    }
  end

  private

  def calculate_total_price(foods)
    foods.sum(&:price)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id(food) %>" class="food-details">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Measurement unit:</strong>
    <%= food.measurement_unit %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= food.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= food.quantity %>
  </p>
</div>

app/views/foods/_form.html.erb
<%= form_with(model: food, class: "food-form") do |form| %>
  <% if food.errors.any? %>
    <div class="error-message">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>
      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :measurement_unit %>
    <%= form.text_field :measurement_unit, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit 'Submit', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/foods/index.html.erb
<p class="success-message"><%= notice %></p>

<div class="header-container">
  <h1>Foods</h1>
  <%= link_to "Add Food", new_food_path, class: "new-food-link" %>
</div>

<div id="foods">
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Measurement Unit</th>
        <th>Unit Price</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.name %></td>
          <td><%= food.measurement_unit %></td>
          <td><%= food.price %></td>
          <td class="button-container">
            <%= button_to "Delete", food, method: :delete, data: { confirm: "Are you sure?" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/foods/new.html.erb
<h1>New food</h1>

<div class="form-container">
  <%= render "form", food: @food %>
</div>

<br />

<div class="button-container">
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<p class="success-message"><%= notice %></p>

<div class="food-details">
  <%= render @food %>
</div>

<div class="button-container">
  <%= link_to "Back to foods", foods_path %>
  <%= button_to "Delete", @food, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
    <%= render partial: "shared/navigation" %>
   <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/public_recipes/index.html.erb
<div>
  <div>
    <h1 class='recipe-name'>Public Recipes</h1>
        <%= link_to 'New Recipe', new_recipe_path, class: 'button-link' %>

  </div>

  <div class="food flex">
    <% @public_recipes.each do |recipe| %>
      <div class='recipe flex'>
        <div class="recipe-details flex">
          <%= link_to recipe_path(recipe) do %>
            <h2> <%= recipe.name %> </h2>
          <% end %>
          <div>
            by: <%=recipe.user.name%>
          </div>
        </div>

        <%= link_to recipe_path(recipe) do %>
          <h4> <%=recipe.description %> </h4>
        <% end %>
      </div>

    <% end %>
  </div>
</div>

app/views/recipe_foods/edit.html.erb
<h2>Modify Ingredient</h2>

<%= form_with(model: @recipe_food, url: recipe_recipe_food_path(@recipe, @recipe_food), method: :patch) do |f| %>
  <div class='new-food'>
    <p>Ingredient: <%= @recipe_food.food.name %></p>
  </div>

  <div class='new-food'>
    <%= f.label :quantity, 'Quantity' %>
    <%= f.number_field :quantity, required: true%>
  </div>

  <div class='new-food'>
    <%= f.submit "Update Ingredient", class: 'button-link' %>
  </div>
<% end %>

app/views/recipe_foods/new.html.erb
<%= link_to 'Add food', new_food_path, class: 'button-link' %>
<%= form_with(model: @recipe_food, url: recipe_recipe_foods_path(@recipe), method: :post) do |f| %>

  <div class='new-food'>
    <%= f.label :food_id, 'Food' %>
    <%= f.collection_select :food_id, Food.order(:name), :id, :name, required: true %>
  </div>

  <div class='new-food'>
    <%= f.label :quantity, 'Quantity' %>
    <%= f.number_field :quantity, required: true %>
  </div>

  <div class='new-food'>
    <%= f.submit 'Add Ingredient', class: 'button-link'  %>
  </div>

<% end %>

app/views/recipes/index.html.erb
<section class="container flex food-placeholder">
<div class="food flex">
  <%= link_to new_recipe_path do %>
    <button>Add Recipe</button>
  <% end %>

<% @recipes.each do |recipe| %>
    <div class='recipe flex'>
      <div class="recipe-details flex">
      <h2><%= link_to recipe.name, recipe_path(recipe) %></h2>
      <% if user_signed_in? && current_user.id == recipe.user_id %>
        <%= button_to "Remove", recipe_path(recipe.id), method: :delete, class: "delete" %>
      <% end %>
      </div>
      <p><%= recipe.description.truncate_words(50, omission: '...') %></p>
    </div>
    <% end %>
    </div>
    </section>

app/views/recipes/new.html.erb
<div class='food-form'>
  <h2 class='new-recipe'>New Recipe</h2>
  <%= form_for @recipe do |f| %>
    <div class='form-group'>
      <%= f.label :name, "Name" %>
      <%= f.text_field :name, placeholder: "Recipe name",  class: "form-control"%>
    </div>
    <div class='form-group'>
      <%= f.label :preparation_time, "Preparation time" %>
      <%= f.text_field :preparation_time, placeholder: "10",  class: "form-control" %>
    </div>
    <div class='form-group'>
      <%= f.label :cooking_time, "Cooking time" %>
      <%= f.text_field :cooking_time, placeholder: "20",  class: "form-control"%>
    </div>
    <div class='form-group'>
      <%= f.label :description, "Description" %>
      <%= f.text_area :description, placeholder: "Recipe description",  class: "form-control" %>
    </div>
    <div>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>

  <% end %>
</div>

app/views/recipes/show.html.erb
<div>
  <h1 class='recipe-name'> <%= @recipe.name %> </h1>

  <div class='recipe-flex'>

    <div>
      <p class='recipe-det'> <span> Preparation Time: </span> <%= @recipe.preparation_time %> minutes </p>
      <p class='recipe-det'> <span> Cooking Time: </span> <%= @recipe.cooking_time %> minutes </p>
      <p class='recipe-det'> <span> Steps: </span> <br/>  <%= @recipe.description %> </p>
    </div>

    <div class='public-box'>
      <%= form_for @recipe, url: { action: :toggle_public } do |f| %>
        <label class='public-label'>
        <span>Public</span>
          <%= f.check_box :public, class: "peer hidden", onchange: "this.form.submit();", checked: @recipe.public? %>
        </label>
      <% end %>      
    </div>

  </div>

  <div>
    <div class='generate'>
      <%= link_to 'Generate Shopping List', shopping_lists_path, class: 'button-link'  %>
      <%= link_to 'Add Ingedrient', new_recipe_recipe_food_path(@recipe), class: 'button-link' %>
    </div>

    <hr>

    <table>
      <thead>
        <tr>
          <th> Food </th>
          <th> Quantity </th>
          <th> Value </th>
          <th class='actions'> Actions </th>
        </tr>
      </thead>
      <tbody>
        <% @recipe_foods.each do |recipe_food| %>
          <tr>
            <td> <%= recipe_food.food.name %> </td>
            <td> <%= recipe_food.quantity %> </td>
            <td> <%= recipe_food.quantity * recipe_food.food.price %> </td>
            <td class='flex-actions'>
                <%= link_to 'Modify', edit_recipe_recipe_food_path(@recipe, recipe_food), class: 'button-link' %> 
                <%= button_to "Remove", recipe_recipe_food_path(@recipe, recipe_food), method: :delete %>
            </td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/shared/_navigation.html.erb
<nav class="navbar">
  <div class="navbar-brand">
    <%= link_to "Recipe App", root_path, class: "navbar-item" %>
  </div>

  <div class="navbar-menu">
    <div class="navbar-item">
      <%= link_to "Foods", foods_path, class: "nav-link #{'active' if current_page?(foods_path)}" %>
      <%= link_to "Recipes", recipes_path, class: "nav-link #{'active' if current_page?(recipes_path)}" %>
      <%= link_to "Public Recipes", public_recipes_path, class: "nav-link #{'active' if current_page?(public_recipes_path)}" %>
      <%= link_to "General shopping list", shopping_lists_path, class: "nav-link #{'active' if current_page?(shopping_lists_path)}" %>
    </div>
    <div class="navbar-end">
      <% if user_signed_in? %>
        <div class="dropdown">
          <button class="dropbtn"><%= current_user.email %> ▼</button>
          <div class="dropdown-content">
            <%= link_to 'Sign Out', destroy_user_session_path, 'data-turbo-method': :delete, class: "navbar-link" %>
          </div>
        </div>
      <% else %>
        <div class="navbar-item">
          <div class="navbar-link-group">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link #{'active' if current_page?(new_user_session_path)}" %>
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link #{'active' if current_page?(new_user_registration_path)}" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/shopping_lists/index.html.erb
<div class="container">
  <h1>Shopping list</h1>
  <div class="result-container">
    <div>
      <p>Amount of food to buy: <%= @result[:missing_items] %></p>
    </div>

    <div>
      <p>
        <p>Total price of food needed: $<%= @result[:total_price] %></p>
      </p>
      
    </div>
  </div>

  <% if @result[:items] %>
    <table>
      <thead>
        <tr>
          <th scope="col">Food</th>
          <th scope="col">Quantity</th>
          <th scope="col">Price</th>
        </tr>
      </thead>
      <tbody>
        <% @result[:items].each do |item| %>
          <tr>
            <td><%= item[:name] %></td>
            <td><%= item[:quantity] %> <%= item[:measurement_unit] %> </td>
            <td>$<%= item[:price] %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <h2 class="no-items">You have all the ingredients.</h2>
  <% end %>
</div>

app/views/users/index.html.erb
<%= render "shared/navigation" %>

<% if user_signed_in? %> 
 <div class="font-bold"> Welcome <%= current_user.name %> </div>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete%> 
<% else %>
  <%= button_to "Sign in", new_user_session_path%> 
<% end %>